name: WebviewNative
on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libwebkit2gtk-4.1-dev xvfb -y
      - name: Get CMake
        uses: lukka/get-cmake@latest
      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja'
          buildPreset: 'ninja'
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "webview-linux64"
          path: ./build

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get CMake
        uses: lukka/get-cmake@latest
      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja'
          buildPreset: 'ninja'
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "webview-mac64"
          path: ./build

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.2
      - name: Get CMake
        uses: lukka/get-cmake@latest
      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'windows'
          buildPreset: 'windows'
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "webview-win64"
          path: ./build
